config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'about', to: 'pages#about', as: :about

  get 'contacnt', to: 'pages#contact', as: :contact

  get 'updates', to: 'pages#updates', as: :updates

  get 'technologies', to: 'pages#technologies', as: :technologies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def updates
  end

  def technologies
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<head>
    <title>HY-TEK Bio</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <div class="master-container">
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    </div>
</body>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="home-banner" style="background-image: linear-gradient(-225deg, rgba(15,52,67,0.5) 0%, rgba(35,122,87,0.4) 50%), url('https://images.pexels.com/photos/343188/pexels-photo-343188.jpeg?w=940&h=650&auto=compress&cs=tinysrgb');">
  <div class="home-banner-content">
    <h1>Harnessing Natural Efficiency</h1>
    <p>To Reclaim the Environment</p>
  </div>
</div>

<h2>more stuff down here</h2>

<!-- linear-gradient(-225deg, rgba(0,50,168,0.6) 0%, rgba(0,76,61,0.6) 50%),  -->
<!-- https://images.pexels.com/photos/534736/pexels-photo-534736.jpeg?w=1260&h=750&auto=compress&cs=tinysrgb -->



<!-- https://images.pexels.com/photos/343188/pexels-photo-343188.jpeg?w=940&h=650&auto=compress&cs=tinysrgb -->

app/views/pages/technologies.html.erb
<h1>Pages#technologies</h1>
<p>Find me in app/views/pages/technologies.html.erb</p>

app/views/pages/updates.html.erb
<h1>Pages#updates</h1>
<p>Find me in app/views/pages/updates.html.erb</p>

app/views/shared/_footer.html.erb
<div class="footer-hytek">





</div>

app/views/shared/_navbar.html.erb
<div class="navbar-hytek">

  <div class="navbar-hytek-logo">
    <%= link_to root_path do %>
      <%= image_tag("hytekbio-white-logo.png") %>
    <% end %>
  </div>

  <div class="navbar-links">
  <ul id="navbar-links">
    <li>
      <%= link_to "Technologies", technologies_path, class: "navbar-link-items" %>
    </li>
    <li>
      <%= link_to "Updates", updates_path, class: "navbar-link-items" %>

    </li>
    <li>
      <%= link_to "About", about_path, class: "navbar-link-items" %>

    </li>
    <li>
      <%= link_to "Contact", contact_path, class: "navbar-link-items" %>

    </li>
  </ul>
  </div>

</div>

<script>
  var url = window.location.pathname;
  var navbarOptions = document.querySelectorAll("a.navbar-link-items");
  navbarOptions.forEach(function(element) {
    if (url == (element.pathname)) {
          element.classList.add("active");
      }
    });
</script>